[build]
  base = "web/"
  command = "pnpm run generate"
  publish = "dist/"
  functions = "functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200